### ISSUE TITLE
error in webtrees 2.0.7 "undefined constant WT_BASE_URL"

### ISSUE THREAD

**Issue by hartenthaler** [bmhm/webtrees-jsonld#42]
I got in webtrees 2.0.7 the following error. The generated web page is empty.

<b>Use of undefined constant WT_BASE_URL - assumed &#039;WT_BASE_URL&#039; (this will throw an Error in a future version of PHP) …/modules_v4/jsonld/src/jsonld/JsonLDTools.php:177</b> <b>#0 …/modules_v4/jsonld/src/jsonld/JsonLDTools.php(177): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, &#039;Use of undefine...&#039;, &#039;/mnt/web312/a3/...&#039;, 177, Array)</b> <b>#1 …/modules_v4/jsonld/src/jsonld/JsonLDTools.php(139): bmhm\WebtreesModules\jsonld\JsonLDTools::createMediaObject(Object(Fisharebest\Webtrees\MediaFile))</b> <b>#2 …/modules_v4/jsonld/module.php(160): bmhm\WebtreesModules\jsonld\JsonLDTools::fillPersonFromRecord(Object(bmhm\WebtreesModules\jsonld\Person), Object(Cissee\WebtreesExt\IndividualExt))</b> <b>#3 …/modules_v4/jsonld/module.php(119): class@anonymous-&gt;createJsonLdForIndividual(Object(Cissee\WebtreesExt\IndividualExt))</b> #4 …/app/Module/ModuleTabTrait.php(117): class@anonymous-&gt;getTabContent(Object(Cissee\WebtreesExt\IndividualExt)) #5 …/app/Http/RequestHandlers/ModuleAction.php(90): class@anonymous-&gt;getTabAction(Object(Nyholm\Psr7\ServerRequest)) #6 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction-&gt;handle(Object(Nyholm\Psr7\ServerRequest)) #7 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler-&gt;process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) <b>#8
--

**Comment by bmhm** [comment]
Yes, I did not update this plugin for 2.x.x.
I need some help for this!

**Comment by bmarwell** [comment]
@hartenthaler can you check the current early access build?
https://github.com/bmarwell/webtrees-jsonld/releases/tag/early-access

**Comment by hartenthaler** [comment]
Thank you for updating that module! What is your intention? How to use that module? You should know that Mr Hemprich is just now developing a module that provides an API for webtrees to read/write genealogical information to a tree. I implemented MCP which allows an AI to "talk" to a tree.
best regards Hermann

**Comment by hartenthaler** [comment]
Sorry: not "I implemented MCP". It should be "He implemented MCP".

**Comment by bmarwell** [comment]
The idea is to make it accessible to search engines.
From the README:

> For more information visit [schema.org](http://schema.org/) or [json-ld.org](http://json-ld.org/).

and

```
# Get JSON-LD data directly using Accept header
curl -H "Accept: application/ld+json" "http://path.to/webtrees/individual.php?pid=I1&ged=AllGED"
```

I am yet to test it properly with 2.x
